[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
sokol =  { version = "*", git = "https://github.com/floooh/sokol-rust.git" }
tobj = "4.0.3"
image = "0.24"
glam = "0.30.1"

[build-dependencies]
cc = "*"
